(() => {
    const root = document.documentElement;
    const page = document.body.dataset.page;
    const storage = { users: 'green-store-users', products: 'green-store-products', session: 'green-store-session', language: 'green-store-language', theme: 'green-store-theme' };
    const seedUsers = [{ id: 'owner-1', fullName: 'Green Store Owner', email: 'owner@green.test', password: 'green123', role: 'owner', profilePic: '' }, { id: 'seller-1', fullName: 'Maya Plants', email: 'maya@green.test', password: 'green123', role: 'owner', profilePic: '' }];
    const seedProducts = [{ id: 'product-1', ownerId: 'seller-1', nameAr: 'نبتة زاميا', nameEn: 'ZZ Plant', category: 'نباتات زينة', price: 85, stock: 12, descriptionAr: 'نبتة أنيقة تتحمل الإضاءة المنخفضة.', descriptionEn: 'A graceful plant that handles low light.', imageUrl: 'https://images.unsplash.com/photo-1509423350716-97f9360b4e09?auto=format&fit=crop&w=900&q=80' }, { id: 'product-2', ownerId: 'seller-1', nameAr: 'بذور ريحان', nameEn: 'Basil Seeds', category: 'بذور', price: 18, stock: 40, descriptionAr: 'بذور عطرية لبداية حديقة مطبخك.', descriptionEn: 'Fragrant seeds for your kitchen garden.', imageUrl: 'https://images.unsplash.com/photo-1618375569909-3c8616cf7733?auto=format&fit=crop&w=900&q=80' }];
    function read(key, fallback) { try { return JSON.parse(localStorage.getItem(key)) ?? fallback; } catch { return fallback; } }
    function write(key, value) { localStorage.setItem(key, JSON.stringify(value)); }
    function users() { const value = read(storage.users, null); if (value) return value; write(storage.users, seedUsers); return seedUsers; }
    function products() { const value = read(storage.products, null); if (value) return value; write(storage.products, seedProducts); return seedProducts; }
    function currentUser() { const id = localStorage.getItem(storage.session); return users().find((user) => user.id === id) || null; }
    function esc(value) { return String(value ?? '').replace(/[&<>"']/g, (char) => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#039;' }[char])); }
    function language() { return localStorage.getItem(storage.language) || 'ar'; }
    function setLanguage(value) { root.lang = value; root.dir = value === 'ar' ? 'rtl' : 'ltr'; document.querySelectorAll('[data-ar][data-en]').forEach((el) => { el.textContent = value === 'ar' ? el.dataset.ar : el.dataset.en; }); const toggle = document.getElementById('languageToggle'); if (toggle) toggle.textContent = value === 'ar' ? 'English' : 'العربية'; localStorage.setItem(storage.language, value); }
    function setTheme(value) { root.dataset.theme = value; const toggle = document.getElementById('themeToggle'); if (toggle) toggle.textContent = value === 'dark' ? '☼' : '◐'; localStorage.setItem(storage.theme, value); }
    function go(path) { window.location.href = path; }
    function protect() { if (!currentUser()) go(page === 'root' ? 'pages/login.html' : 'login.html'); }
    function showMessage(text) { const el = document.getElementById('authMessage') || document.getElementById('pageMessage'); if (!el) return; el.textContent = text; el.hidden = false; }
    function setupCommon() { document.getElementById('languageToggle')?.addEventListener('click', () => setLanguage(language() === 'ar' ? 'en' : 'ar')); document.getElementById('themeToggle')?.addEventListener('click', () => setTheme((localStorage.getItem(storage.theme) || 'light') === 'dark' ? 'light' : 'dark')); document.getElementById('logoutButton')?.addEventListener('click', () => { localStorage.removeItem(storage.session); go(page === 'dashboard' || page === 'marketplace' ? 'login.html' : 'pages/login.html'); }); setLanguage(language()); setTheme(localStorage.getItem(storage.theme) || 'light'); }
    function setupAuth() { if (currentUser()) { go('index.html'); return; } document.querySelectorAll('.auth-tab').forEach((tab) => tab.addEventListener('click', () => { document.querySelectorAll('.auth-tab').forEach((item) => item.classList.toggle('active', item === tab)); document.querySelectorAll('.auth-form').forEach((form) => form.classList.toggle('active', form.id === `${tab.dataset.tab}Form`)); })); document.getElementById('loginForm')?.addEventListener('submit', (event) => { event.preventDefault(); const data = new FormData(event.currentTarget); const user = users().find((item) => item.email.toLowerCase() === data.get('email').toLowerCase() && item.password === data.get('password')); if (!user) { showMessage(language() === 'ar' ? 'بيانات الدخول غير صحيحة.' : 'Invalid email or password.'); return; } localStorage.setItem(storage.session, user.id); go('index.html'); }); document.getElementById('registerForm')?.addEventListener('submit', (event) => { event.preventDefault(); const data = new FormData(event.currentTarget); const email = data.get('email').trim().toLowerCase(); const list = users(); if (list.some((item) => item.email.toLowerCase() === email)) { showMessage(language() === 'ar' ? 'البريد مستخدم بالفعل.' : 'Email is already registered.'); return; } const user = { id: `user-${Date.now()}`, fullName: data.get('full_name').trim(), email, password: data.get('password'), role: list.length ? 'customer' : 'owner', profilePic: '' }; list.push(user); write(storage.users, list); localStorage.setItem(storage.session, user.id); go('index.html'); }); }
    function applyImages() { document.querySelectorAll('[data-image]').forEach((el) => { if (el.dataset.image) el.style.setProperty('--image', `url("${el.dataset.image.replace(/"/g, '%22')}")`); }); }
    function productCard(product, controls = false) { const seller = users().find((user) => user.id === product.ownerId)?.fullName || 'Green Store'; return `<article class="product-card" data-product-card data-category="${esc(product.category)}" data-search="${esc(`${product.nameAr} ${product.nameEn} ${product.descriptionAr} ${product.descriptionEn}`)}"><div class="product-image" data-image="${esc(product.imageUrl)}"><span class="category-tag">${esc(product.category)}</span></div><div class="product-body">${controls ? '' : `<div class="seller-badge"><span>●</span> <span data-ar="يباع بواسطة: ${esc(seller)}" data-en="Sold by: ${esc(seller)}">يباع بواسطة: ${esc(seller)}</span></div>`}<h3 data-ar="${esc(product.nameAr)}" data-en="${esc(product.nameEn)}">${esc(product.nameAr)}</h3><p class="product-description" data-ar="${esc(product.descriptionAr)}" data-en="${esc(product.descriptionEn)}">${esc(product.descriptionAr)}</p><div class="product-meta"><strong>${Number(product.price).toFixed(2)} <small>SAR</small></strong><span class="stock" data-ar="المخزون: ${product.stock}" data-en="Stock: ${product.stock}">المخزون: ${product.stock}</span></div>${controls ? `<div class="owner-controls"><a href="#productForm" data-edit-product="${esc(JSON.stringify(product))}" data-ar="تعديل" data-en="Edit">تعديل</a><a class="delete-link" href="#" data-delete-product="${product.id}" data-ar="حذف" data-en="Delete">حذف</a></div>` : ''}</div></article>`; }
    function setupDashboard() { protect(); const user = currentUser(); if (!user) return; const isOwner = user.role === 'owner'; document.getElementById('userChip').innerHTML = `<span class="avatar">${esc(user.fullName.slice(0, 1))}</span>${esc(user.fullName)}${isOwner ? '<b data-ar="مالك" data-en="Owner">مالك</b>' : ''}`; document.getElementById('profileName').value = user.fullName; document.getElementById('profileEmail').value = user.email; document.getElementById('profilePic').value = user.profilePic || ''; if (!isOwner) { document.getElementById('ownerArea').innerHTML = '<div class="customer-callout"><p class="eyebrow" data-ar="تصفح واكتشف" data-en="Browse and discover">تصفح واكتشف</p><h2 data-ar="اكتشف منتجات البائعين الآخرين في السوق." data-en="Discover products from other sellers in the marketplace.">اكتشف منتجات البائعين الآخرين في السوق.</h2><a class="primary-button" href="marketplace.html" data-ar="اذهب إلى السوق" data-en="Go to marketplace">اذهب إلى السوق</a></div>'; document.getElementById('productForm').hidden = true; return; } renderOwnerProducts(); document.getElementById('profileForm').addEventListener('submit', (event) => { event.preventDefault(); const list = users(); const index = list.findIndex((item) => item.id === user.id); list[index].fullName = document.getElementById('profileName').value.trim(); list[index].email = document.getElementById('profileEmail').value.trim(); list[index].profilePic = document.getElementById('profilePic').value.trim(); write(storage.users, list); showMessage(language() === 'ar' ? 'تم حفظ الملف الشخصي.' : 'Profile saved.'); }); document.getElementById('productFormElement').addEventListener('submit', (event) => { event.preventDefault(); const id = document.getElementById('productId').value; const item = { id: id || `product-${Date.now()}`, ownerId: user.id, nameAr: document.getElementById('nameAr').value.trim(), nameEn: document.getElementById('nameEn').value.trim(), category: document.getElementById('category').value, price: Number(document.getElementById('price').value), stock: Number(document.getElementById('stock').value), descriptionAr: document.getElementById('descriptionAr').value.trim(), descriptionEn: document.getElementById('descriptionEn').value.trim(), imageUrl: document.getElementById('imageUrl').value.trim() }; const list = products(); const index = list.findIndex((product) => product.id === id); if (index >= 0) list[index] = item; else list.unshift(item); write(storage.products, list); event.currentTarget.reset(); document.getElementById('productId').value = ''; renderOwnerProducts(); showMessage(language() === 'ar' ? 'تم حفظ المنتج.' : 'Product saved.'); }); }
    function renderOwnerProducts() { const user = currentUser(); const mine = products().filter((item) => item.ownerId === user.id); document.getElementById('productCount').textContent = mine.length; document.getElementById('myProducts').innerHTML = mine.length ? mine.map((item) => productCard(item, true)).join('') : '<div class="empty-state" data-ar="أضف أول منتج لك من النموذج أدناه." data-en="Add your first product from the form below.">أضف أول منتج لك من النموذج أدناه.</div>'; applyImages(); setLanguage(language()); document.querySelectorAll('[data-delete-product]').forEach((button) => button.addEventListener('click', (event) => { event.preventDefault(); if (confirm(language() === 'ar' ? 'حذف هذا المنتج؟' : 'Delete this product?')) { write(storage.products, products().filter((item) => item.id !== button.dataset.deleteProduct)); renderOwnerProducts(); } })); document.querySelectorAll('[data-edit-product]').forEach((button) => button.addEventListener('click', () => { const item = JSON.parse(button.dataset.editProduct); const fields = { productId: 'id', nameAr: 'nameAr', nameEn: 'nameEn', category: 'category', price: 'price', stock: 'stock', imageUrl: 'imageUrl', descriptionAr: 'descriptionAr', descriptionEn: 'descriptionEn' }; Object.entries(fields).forEach(([id, key]) => { document.getElementById(id).value = item[key]; }); document.getElementById('productSubmit').dataset.ar = 'حفظ التعديل'; document.getElementById('productSubmit').dataset.en = 'Save changes'; setLanguage(language()); })); }
    function setupMarketplace() { protect(); if (!currentUser()) return; renderMarketplace(); document.getElementById('marketplaceSearch').addEventListener('input', renderMarketplace); document.getElementById('marketplaceCategory').addEventListener('change', renderMarketplace); }
    function renderMarketplace() { const user = currentUser(); const query = document.getElementById('marketplaceSearch').value.toLowerCase().trim(); const category = document.getElementById('marketplaceCategory').value; const list = products().filter((item) => item.ownerId !== user.id && (!category || item.category === category) && `${item.nameAr} ${item.nameEn} ${item.descriptionAr} ${item.descriptionEn}`.toLowerCase().includes(query)); document.getElementById('marketplaceGrid').innerHTML = list.map((item) => productCard(item)).join(''); document.getElementById('filterEmpty').hidden = list.length > 0; applyImages(); setLanguage(language()); }
    setupCommon(); if (page === 'root') go(currentUser() ? 'pages/index.html' : 'pages/login.html'); if (page === 'login') setupAuth(); if (page === 'dashboard') setupDashboard(); if (page === 'marketplace') setupMarketplace();
})();